// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ged_fdl_razor.Data;

#nullable disable

namespace ged_fdl_razor.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("ged_fdl_razor.Models.Commune", b =>
                {
                    b.Property<int>("CommuneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CommuneID");

                    b.ToTable("Communes");
                });

            modelBuilder.Entity("ged_fdl_razor.Models.Document", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Contenu")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("DateUpload")
                        .HasColumnType("TEXT");

                    b.Property<int>("DossierFinancementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("Taille")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("DocumentID");

                    b.HasIndex("DossierFinancementId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ged_fdl_razor.Models.DossierFinancement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommuneId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateSoumission")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("TEXT");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommuneId");

                    b.ToTable("DossiersFinancement");
                });

            modelBuilder.Entity("ged_fdl_razor.Models.Remarque", b =>
                {
                    b.Property<int>("RemarqueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommuneId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<int>("DossierFinancementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("RemarqueID");

                    b.HasIndex("CommuneId");

                    b.HasIndex("DossierFinancementId");

                    b.ToTable("Remarques");
                });

            modelBuilder.Entity("ged_fdl_razor.Models.Document", b =>
                {
                    b.HasOne("ged_fdl_razor.Models.DossierFinancement", "DossierFinancement")
                        .WithMany()
                        .HasForeignKey("DossierFinancementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DossierFinancement");
                });

            modelBuilder.Entity("ged_fdl_razor.Models.DossierFinancement", b =>
                {
                    b.HasOne("ged_fdl_razor.Models.Commune", "Commune")
                        .WithMany("Dossiers")
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commune");
                });

            modelBuilder.Entity("ged_fdl_razor.Models.Remarque", b =>
                {
                    b.HasOne("ged_fdl_razor.Models.Commune", "Commune")
                        .WithMany()
                        .HasForeignKey("CommuneId");

                    b.HasOne("ged_fdl_razor.Models.DossierFinancement", "DossierFinancement")
                        .WithMany("Remarques")
                        .HasForeignKey("DossierFinancementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commune");

                    b.Navigation("DossierFinancement");
                });

            modelBuilder.Entity("ged_fdl_razor.Models.Commune", b =>
                {
                    b.Navigation("Dossiers");
                });

            modelBuilder.Entity("ged_fdl_razor.Models.DossierFinancement", b =>
                {
                    b.Navigation("Remarques");
                });
#pragma warning restore 612, 618
        }
    }
}
